### PR TITLE
Use stat from /usr/bin and -e option in sed invocation

### LINKED ISSUE #26: napi.sh doesn't work on OS X when coreutils are installed
It looks like `napi.sh` tries to use GNU version of `stat` command when `coreutils` are installed using Homebrew.

```
#00:0001 --- 875: weryfikacja argumentow
#00:0002 --- 878: sprawdzam dane uwierzytelniania
#00:0003 --- 884: normalizacja parametrow numerycznych
#00:0004 --- 891: sprawdzam wybrane kodowanie
#00:0005 --- 830: sprawdzam narzedzie 7z
#00:0006 -- 841: 7z wykryty jako [7za]
#00:0007 --- 901: sprawdzam id
#00:0008 --- 907: id zweryfikowane pomyslnie [NapiProjektPython]
#00:0009 --- 925: sprawdzam logfile
#00:0010 --- 939: sprawdzam wybrany jezyk
#00:0011 --- 953: jezyk znaleziony, index = 24
#00:0012 --- 960: sprawdzam format
#00:0013 --- 965: sprawdzam wybrane narzedzie fps
#00:0014 --- 970: sprawdzam zewnetrzny skrypt
#00:0015 -- 2738: ustawiam STDOUT
#00:0016 - wywolano o Thu Mar 26 20:30:02 CET 2015
#00:0017 - system: darwin, forkow: 8, wersja: v1.3.4
#00:0018 - =================================================
#00:0019 - napi.sh od wersji 1.3.1 domyslnie uzywa nowego
#00:0020 - API (napiprojekt-3)
#00:0021 - Jezeli zauwazysz jakies problemy z nowym API
#00:0022 - albo skrypt dziala zbyt wolno, mozesz wrocic do
#00:0023 - starego API korzystajac z opcji --id pynapi
#00:0024 - =================================================
#00:0025 -- 2747: przygotowuje liste plikow...
stat: invalid option -- '%'
Try 'stat --help' for more information.
./napi.sh: line 1979: [: : integer expression expected
#00:0026 - znaleziono 0 plikow...
#00:0027 -- 2760: przywracam STDOUT
```

### PR DESCRIPTION
**Pull request by mstrzele**
Fixes #26 and #28.

### CODE REVIEW

**Comment by dagon666** [comment]
I can't accept this pull request. bashnapi is mostly dedicated to embedded systems which may have sed/stat (or other tools) installed in a completely non-standard locations. Hardcoding the path is the worst thing that can be done in this regard.

**Comment by mstrzele** [comment]
I changed the PR. The only path that is hard-coded, is for `stat` in OS X. I think that there's no embedded systems with OS X installed...

**Comment by dagon666** [comment]
I'm sorry but this is still not good enough. Please, retest the tip of dev branch to check if the proposed correction for stat tool detection works. I need to investigate the sed problem deeper with some virtual machine since I don't have access to Mac machine at the moment.

**Comment by mstrzele** [comment]
Your fix works like a charm! :+1: Thanks for that! I can agree that my solution wasn't the best but it worked for me.

If you want to do the tests and you don't have access to Mac, you can use FreeBSD 7.4 (the tools in OS X are in the same versions).

It seems that the `sed` issue is really not so easy to fix (according to [this post on StackOverflow](http://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux)).

**Comment by dagon666** [comment]
I'm glad to hear that. Thanks for the tip as well. I'll try to experiment with freebsd vm to debug the script and provide a solution to the install.sh sed problem.

**Pull request closed without merging**
